### ISSUE TITLE
Funktionsumfang

### ISSUE THREAD

**Issue by dmolineus** [hofff/contao-contact-profiles#1]
Folgende Features sehe ich derzeit vor:

 - Zusätzlicher Bereich Ansprechpartner mit folgenden Feldern:
     - Name
     - Anrede  
     - Jobtitel
     - E-Mail
     - Telefon
     - Mobil
     - Fax
     - Anrede
     - Bild
 - Inhaltselement Ansprechpartner
 - Modul Ansprechpartner

Im CE/Modul können mehrere Ansprechpartner ausgewählt werden und die anzuzeigenden Felder definiert werden.

Wenn noch was fehlt, bitter ergänzen.

**Comment by dmolineus** [comment]
Eine Frage wäre, ob eine Kategorisierung notwending ist. Also ein analoger Aufbau wie bei News-Archive -> News.

**Comment by frontendschlampe** [comment]
> Eine Frage wäre, ob eine Kategorisierung notwending ist. Also ein analoger Aufbau wie bei News-Archive -> News.

Du meinst, dass man die einzelnen Ansprechpartner noch gesondert unterteilen kann z.B. Gruppe Vertrieb, Management etc.

Wir haben bei uns folgende Felder:

- **Vorname**
- **Nachname**
- E-Mail-Adresse
- Telefon
- Mobil
- Fax
- Bild
- Profession (=Jobtitel)
- **Fachgebiete** (ist eine Checkboxliste, die man separat pflegen kann)
- **Kurzbeschreibung**
- **Langbeschreibung**
- **Social Media Profile** (Facebook, Google+, Pinterest, Twitter, LinkedIn, Xing)
- **Link zur Detailseite**
- **Veröffentlicht**

Die müssten wir einfach mal zusammen durchgehen und überlegen, was Sinn macht.

**Comment by frontendschlampe** [comment]
Wir legen also fest:

**persönliche Informationen:**

1. Anrede (Input)
2. Titel (Input)
3. Vorname (Input)
4. Nachname (Input)
5. Position (Input)
6. Profession (Input)
7. Bild (FileTree)

**Kontaktinformationen:**

1. Telefon (Input)
2. Mobil (Input)
3. Fax (Input)
4. E-Mail-Adresse (Input)
5. Social Media Profile (separater Einstellungspunkt) (MCW)

**Details:**

1. Kurzbeschreibung (TinyMCE)
2. Langbeschreibung (TinyMCE)
3. Zuständigkeiten (separater Einstellungspunkt) (Checkbox)
4. Link zur Detailseite (PageTree)

**Veröffentlichung:**

1. Veröffentlicht (Checkbox)

**Comment by dmolineus** [comment]
Die Features sind soweit implementiert. Derzeit fehlt noch die deutsche Übersetzung und ggf. Icons für die Bereiche "Social Accounts" und "Responsibilities". @frontendschlampe Soll ich mich noch um die deutschsprachigen Labels kümmern?

**Comment by frontendschlampe** [comment]
musst du nicht ... das mache ich dann
